export const SEED_SHIPMENTS = [
  {
    name: 'KRUX LOGISTICS PIPELINE',
    cif_value_usd: 25000,
    pvoc_deadline: '2026-04-23',
    origin_port: 'Mumbai, India',
    regulatory_body: 'PPB',
    risk_flag_status: 'AMBER',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 33257.50,
    total_landed_cost_kes: 4290218,
    storage_rate_per_day: 150,
    composite_risk_score: 8,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
  {
    name: 'KRUX PHARMA PVOC SHIPMENT',
    cif_value_usd: 18000,
    pvoc_deadline: '2026-05-01',
    origin_port: 'Chennai, India',
    regulatory_body: 'KEBS',
    risk_flag_status: 'AMBER',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 27195.00,
    total_landed_cost_kes: 3508395,
    storage_rate_per_day: 120,
    composite_risk_score: 7,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
  {
    name: 'KRUX FERTILIZER SHIPMENT',
    cif_value_usd: 32000,
    pvoc_deadline: '2026-05-05',
    origin_port: 'Shanghai, China',
    regulatory_body: 'PCPB',
    risk_flag_status: 'GREEN',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 42832.00,
    total_landed_cost_kes: 5526528,
    storage_rate_per_day: 200,
    composite_risk_score: 4,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
  {
    name: 'KRUX AGRO KEPHIS SHIPMENT',
    cif_value_usd: 14500,
    pvoc_deadline: '2026-05-08',
    origin_port: 'Dubai, UAE',
    regulatory_body: 'KEPHIS',
    risk_flag_status: 'AMBER',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 19473.75,
    total_landed_cost_kes: 2514079,
    storage_rate_per_day: 100,
    composite_risk_score: 6,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
  {
    name: 'KRUX WHO-GMP PHARMA SHIPMENT',
    cif_value_usd: 45000,
    pvoc_deadline: '2026-05-10',
    origin_port: 'Amsterdam, Netherlands',
    regulatory_body: 'WHO-GMP',
    risk_flag_status: 'GREEN',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 67737.50,
    total_landed_cost_kes: 8738138,
    storage_rate_per_day: 300,
    composite_risk_score: 3,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
  {
    name: 'KRUX SUPPLEMENTS KEBS SHIPMENT',
    cif_value_usd: 9500,
    pvoc_deadline: '2026-05-12',
    origin_port: 'London, UK',
    regulatory_body: 'KEBS',
    risk_flag_status: 'GREEN',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 15800.00,
    total_landed_cost_kes: 2038200,
    storage_rate_per_day: 80,
    composite_risk_score: 3,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
  {
    name: 'KRUX GREEN ENERGY EPRA SHIPMENT',
    cif_value_usd: 67000,
    pvoc_deadline: '2026-05-15',
    origin_port: 'Shenzhen, China',
    regulatory_body: 'EPRA',
    risk_flag_status: 'GREEN',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 95000.00,
    total_landed_cost_kes: 12255000,
    storage_rate_per_day: 400,
    composite_risk_score: 2,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
  {
    name: 'KRUX KRA CUSTOMS SHIPMENT',
    cif_value_usd: 28000,
    pvoc_deadline: '2026-05-18',
    origin_port: 'Singapore',
    regulatory_body: 'KRA',
    risk_flag_status: 'AMBER',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 40000.00,
    total_landed_cost_kes: 5160000,
    storage_rate_per_day: 180,
    composite_risk_score: 6,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
  {
    name: 'KRUX NEMA CONSTRUCTION SHIPMENT',
    cif_value_usd: 54000,
    pvoc_deadline: '2026-05-20',
    origin_port: 'Jebel Ali, UAE',
    regulatory_body: 'NEMA',
    risk_flag_status: 'RED',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 76500.00,
    total_landed_cost_kes: 9868500,
    storage_rate_per_day: 350,
    composite_risk_score: 9,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
  {
    name: 'KRUX KEBS MACHINERY SHIPMENT',
    cif_value_usd: 89000,
    pvoc_deadline: '2026-05-25',
    origin_port: 'Tokyo, Japan',
    regulatory_body: 'KEBS',
    risk_flag_status: 'GREEN',
    remediation_status: 'OPEN' as const,
    total_landed_cost_usd: 107000.00,
    total_landed_cost_kes: 13803000,
    storage_rate_per_day: 500,
    composite_risk_score: 2,
    ai_compliance_brief: null,
    ai_remediation_steps: null,
    ai_document_checklist: null,
    ai_tax_quotation: null,
  },
]
