-- KRUXVON: Step 4 of 10 — Manufacturers and clearing agents

CREATE TABLE manufacturers (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id         UUID NOT NULL REFERENCES organizations(id),
  company_name            TEXT NOT NULL,
  trading_name            TEXT,
  country                 TEXT NOT NULL DEFAULT 'IN',
  city                    TEXT,
  state                   TEXT,
  factory_address         TEXT,
  registered_address      TEXT,
  website                 TEXT,
  registration_number     TEXT,
  primary_contact_name    TEXT,
  primary_contact_email   TEXT,
  primary_contact_phone   TEXT,
  whatsapp_number         TEXT,
  account_manager_name    TEXT,
  product_categories      TEXT[],
  industries              TEXT[],
  export_markets          TEXT[],
  annual_revenue_usd      DECIMAL(14,2),
  annual_capacity_usd     DECIMAL(14,2),
  employee_count          INTEGER,
  years_in_business       INTEGER,
  factory_size_sqm        INTEGER,
  is_vetted               BOOLEAN DEFAULT false,
  vetting_date            DATE,
  vetting_score           INTEGER CHECK (vetting_score BETWEEN 0 AND 100),
  vetting_notes           TEXT,
  next_vetting_due        DATE,
  is_preferred_supplier   BOOLEAN DEFAULT false,
  is_blacklisted          BOOLEAN DEFAULT false,
  blacklist_reason        TEXT,
  blacklisted_at          TIMESTAMPTZ,
  reliability_score       INTEGER DEFAULT 50 CHECK (reliability_score BETWEEN 0 AND 100),
  financial_risk_score    INTEGER DEFAULT 50 CHECK (financial_risk_score BETWEEN 0 AND 100),
  overall_risk            risk_flag DEFAULT 'AMBER',
  total_orders_placed     INTEGER DEFAULT 0,
  orders_on_time          INTEGER DEFAULT 0,
  orders_disputed         INTEGER DEFAULT 0,
  minimum_order_usd       DECIMAL(10,2),
  typical_payment_terms   TEXT,
  typical_lead_time_days  INTEGER,
  accepts_lc              BOOLEAN DEFAULT false,
  accepted_currencies     TEXT[] DEFAULT ARRAY['USD'],
  notes                   TEXT,
  created_by              UUID REFERENCES users(id),
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW(),
  deleted_at              TIMESTAMPTZ
);

CREATE TABLE clearing_agents (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id       UUID NOT NULL REFERENCES organizations(id),
  agent_organization_id UUID REFERENCES organizations(id),
  company_name          TEXT NOT NULL,
  license_number        TEXT,
  license_expiry        DATE,
  license_status        license_status DEFAULT 'ACTIVE',
  primary_contact       TEXT,
  email                 TEXT,
  phone                 TEXT,
  whatsapp_number       TEXT,
  ports_covered         TEXT[] DEFAULT ARRAY['Mombasa'],
  specializations       TEXT[],
  regulatory_clearances TEXT[],
  performance_score     INTEGER DEFAULT 50 CHECK (performance_score BETWEEN 0 AND 100),
  avg_clearance_days    DECIMAL(4,1),
  total_shipments_cleared INTEGER DEFAULT 0,
  disputes_count        INTEGER DEFAULT 0,
  is_preferred          BOOLEAN DEFAULT false,
  is_active             BOOLEAN DEFAULT true,
  notes                 TEXT,
  created_by            UUID REFERENCES users(id),
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);
