-- KRUXVON: Step 5 of 10 — Shipments (purchase_order_id FK added in step 6)

CREATE SEQUENCE IF NOT EXISTS shipment_seq START 1;

CREATE TABLE shipments (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id         UUID NOT NULL REFERENCES organizations(id),
  reference_number        TEXT UNIQUE NOT NULL DEFAULT '',
  name                    TEXT NOT NULL,
  manufacturer_id         UUID REFERENCES manufacturers(id),
  clearing_agent_id       UUID REFERENCES clearing_agents(id),
  regulatory_body_id      UUID REFERENCES regulatory_bodies(id),
  regulatory_rule_id      UUID REFERENCES regulatory_rules(id),
  purchase_order_id       UUID,
  origin_port             TEXT NOT NULL,
  destination_port        TEXT NOT NULL DEFAULT 'Mombasa',
  origin_country          TEXT,
  hs_code                 TEXT,
  product_description     TEXT,
  quantity                DECIMAL(12,3),
  unit                    TEXT,
  weight_kg               DECIMAL(10,2),
  container_type          TEXT,
  vessel_name             TEXT,
  bl_number               TEXT,
  cif_value_usd           DECIMAL(12,2) NOT NULL,
  import_duty_usd         DECIMAL(10,2),
  vat_usd                 DECIMAL(10,2),
  idf_levy_usd            DECIMAL(10,2),
  rdl_levy_usd            DECIMAL(10,2),
  pvoc_fee_usd            DECIMAL(8,2),
  clearing_fee_usd        DECIMAL(8,2),
  storage_accrued_usd     DECIMAL(10,2),
  total_landed_cost_usd   DECIMAL(12,2),
  total_landed_cost_kes   DECIMAL(14,2),
  exchange_rate_used      DECIMAL(8,4) DEFAULT 129,
  storage_rate_per_day    DECIMAL(8,2),
  pvoc_deadline           DATE,
  eta                     DATE,
  actual_arrival_date     DATE,
  clearance_date          DATE,
  risk_flag_status        risk_flag NOT NULL DEFAULT 'AMBER',
  remediation_status      remediation_status NOT NULL DEFAULT 'OPEN',
  shipment_status         shipment_status NOT NULL DEFAULT 'DRAFT',
  composite_risk_score    INTEGER DEFAULT 5 CHECK (composite_risk_score BETWEEN 0 AND 10),
  open_action_count       INTEGER DEFAULT 0,
  ai_compliance_brief     TEXT,
  ai_remediation_steps    TEXT,
  ai_document_checklist   TEXT,
  ai_tax_quotation        TEXT,
  ai_generated_at         TIMESTAMPTZ,
  notes                   TEXT,
  internal_notes          TEXT,
  created_by              UUID REFERENCES users(id),
  assigned_to             UUID REFERENCES users(id),
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW(),
  deleted_at              TIMESTAMPTZ
);
