-- KRUXVON: Step 7 of 10 — All dependent tables

CREATE TABLE shipment_documents (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shipment_id      UUID NOT NULL REFERENCES shipments(id),
  organization_id  UUID NOT NULL REFERENCES organizations(id),
  document_type    TEXT NOT NULL,
  document_name    TEXT NOT NULL,
  file_url         TEXT,
  file_size_bytes  INTEGER,
  mime_type        TEXT,
  is_required      BOOLEAN DEFAULT true,
  is_verified      BOOLEAN DEFAULT false,
  verified_by      UUID REFERENCES users(id),
  verified_at      TIMESTAMPTZ,
  expires_at       DATE,
  rejection_reason TEXT,
  notes            TEXT,
  uploaded_by      UUID REFERENCES users(id),
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE shipment_timeline (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shipment_id     UUID NOT NULL REFERENCES shipments(id),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  event_type      TEXT NOT NULL,
  event_title     TEXT NOT NULL,
  event_detail    TEXT,
  old_value       TEXT,
  new_value       TEXT,
  created_by      UUID REFERENCES users(id),
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE manufacturer_licenses (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  manufacturer_id        UUID NOT NULL REFERENCES manufacturers(id),
  organization_id        UUID NOT NULL REFERENCES organizations(id),
  license_type           TEXT NOT NULL,
  license_name           TEXT NOT NULL,
  license_number         TEXT,
  issuing_body           TEXT NOT NULL,
  issuing_country        TEXT NOT NULL,
  scope                  TEXT,
  issued_date            DATE,
  expiry_date            DATE NOT NULL,
  renewal_lead_time_days INTEGER DEFAULT 90,
  status                 license_status NOT NULL DEFAULT 'ACTIVE',
  alert_60_sent_at       TIMESTAMPTZ,
  alert_30_sent_at       TIMESTAMPTZ,
  alert_7_sent_at        TIMESTAMPTZ,
  alert_expired_sent_at  TIMESTAMPTZ,
  document_url           TEXT,
  is_verified            BOOLEAN DEFAULT false,
  verified_by            UUID REFERENCES users(id),
  verified_at            TIMESTAMPTZ,
  notes                  TEXT,
  created_by             UUID REFERENCES users(id),
  created_at             TIMESTAMPTZ DEFAULT NOW(),
  updated_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE factory_audits (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  manufacturer_id         UUID NOT NULL REFERENCES manufacturers(id),
  organization_id         UUID NOT NULL REFERENCES organizations(id),
  audit_agency_id         UUID REFERENCES audit_agencies(id),
  audit_type              TEXT NOT NULL,
  audit_scope             TEXT,
  status                  audit_status NOT NULL DEFAULT 'SCHEDULED',
  scheduled_date          DATE,
  conducted_date          DATE,
  report_due_date         DATE,
  report_submitted_date   DATE,
  overall_score           INTEGER CHECK (overall_score BETWEEN 0 AND 100),
  quality_mgmt_score      INTEGER CHECK (quality_mgmt_score BETWEEN 0 AND 100),
  regulatory_score        INTEGER CHECK (regulatory_score BETWEEN 0 AND 100),
  capacity_score          INTEGER CHECK (capacity_score BETWEEN 0 AND 100),
  financial_health_score  INTEGER CHECK (financial_health_score BETWEEN 0 AND 100),
  worker_conditions_score INTEGER CHECK (worker_conditions_score BETWEEN 0 AND 100),
  critical_findings       TEXT[],
  major_findings          TEXT[],
  minor_findings          TEXT[],
  recommendations         TEXT,
  corrective_action_plan  TEXT,
  corrective_action_due   DATE,
  report_url              TEXT,
  photos_url              TEXT[],
  is_approved             BOOLEAN,
  approval_expires        DATE,
  failure_reason          TEXT,
  india_recognized        BOOLEAN DEFAULT false,
  kenya_recognized        BOOLEAN DEFAULT false,
  lead_auditor_name       TEXT,
  audit_fee_usd           DECIMAL(8,2),
  kruxvon_fee_usd         DECIMAL(8,2),
  created_by              UUID REFERENCES users(id),
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE po_milestones (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_order_id  UUID NOT NULL REFERENCES purchase_orders(id),
  organization_id    UUID NOT NULL REFERENCES organizations(id),
  name               TEXT NOT NULL,
  description        TEXT,
  milestone_type     TEXT,
  sequence_number    INTEGER,
  due_date           DATE NOT NULL,
  completed_date     DATE,
  is_completed       BOOLEAN DEFAULT false,
  is_overdue         BOOLEAN DEFAULT false,
  triggers_payment   BOOLEAN DEFAULT false,
  payment_amount_usd DECIMAL(10,2),
  evidence_required  TEXT[],
  evidence_urls      TEXT[],
  notes              TEXT,
  created_at         TIMESTAMPTZ DEFAULT NOW(),
  updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE financial_risk_signals (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  manufacturer_id  UUID NOT NULL REFERENCES manufacturers(id),
  signal_type      TEXT NOT NULL,
  severity         risk_flag NOT NULL DEFAULT 'AMBER',
  title            TEXT NOT NULL,
  description      TEXT NOT NULL,
  source           TEXT,
  evidence_url     TEXT,
  detected_at      TIMESTAMPTZ DEFAULT NOW(),
  is_resolved      BOOLEAN DEFAULT false,
  resolved_at      TIMESTAMPTZ,
  resolution_notes TEXT,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE product_certifications (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id       UUID NOT NULL REFERENCES organizations(id),
  manufacturer_id       UUID REFERENCES manufacturers(id),
  audit_agency_id       UUID REFERENCES audit_agencies(id),
  product_name          TEXT NOT NULL,
  product_description   TEXT,
  product_category      TEXT NOT NULL,
  hs_code               TEXT,
  brand_name            TEXT,
  model_number          TEXT,
  certification_type    TEXT NOT NULL,
  certificate_number    TEXT,
  status                cert_status NOT NULL DEFAULT 'PENDING',
  india_cert_required   BOOLEAN DEFAULT false,
  india_approved        BOOLEAN DEFAULT false,
  india_cert_number     TEXT,
  india_cert_body       TEXT,
  india_cert_url        TEXT,
  india_issued_date     DATE,
  india_expiry_date     DATE,
  kenya_cert_required   BOOLEAN DEFAULT true,
  kenya_approved        BOOLEAN DEFAULT false,
  kenya_cert_number     TEXT,
  kenya_cert_body       TEXT DEFAULT 'KEBS',
  kenya_cert_url        TEXT,
  kenya_issued_date     DATE,
  kenya_expiry_date     DATE,
  lab_test_required     BOOLEAN DEFAULT true,
  lab_test_completed    BOOLEAN DEFAULT false,
  lab_name              TEXT,
  lab_test_date         DATE,
  lab_report_url        TEXT,
  test_parameters       TEXT[],
  test_passed           BOOLEAN,
  alert_60_sent_at      TIMESTAMPTZ,
  alert_30_sent_at      TIMESTAMPTZ,
  certification_fee_usd DECIMAL(8,2),
  lab_fee_usd           DECIMAL(8,2),
  kruxvon_fee_usd       DECIMAL(8,2),
  notes                 TEXT,
  created_by            UUID REFERENCES users(id),
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE agent_shipment_assignments (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  clearing_agent_id UUID NOT NULL REFERENCES clearing_agents(id),
  shipment_id       UUID NOT NULL REFERENCES shipments(id),
  organization_id   UUID NOT NULL REFERENCES organizations(id),
  assigned_at       TIMESTAMPTZ DEFAULT NOW(),
  assigned_by       UUID REFERENCES users(id),
  status            TEXT DEFAULT 'ACTIVE',
  fee_agreed_usd    DECIMAL(8,2),
  notes             TEXT,
  UNIQUE(clearing_agent_id, shipment_id)
);

CREATE TABLE alerts (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID NOT NULL REFERENCES organizations(id),
  alert_type       alert_type NOT NULL,
  severity         risk_flag NOT NULL DEFAULT 'AMBER',
  title            TEXT NOT NULL,
  message          TEXT NOT NULL,
  action_required  TEXT,
  shipment_id      UUID REFERENCES shipments(id),
  manufacturer_id  UUID REFERENCES manufacturers(id),
  license_id       UUID REFERENCES manufacturer_licenses(id),
  purchase_order_id UUID REFERENCES purchase_orders(id),
  certification_id UUID REFERENCES product_certifications(id),
  clearing_agent_id UUID REFERENCES clearing_agents(id),
  channels         alert_channel[] DEFAULT ARRAY['IN_APP'::alert_channel, 'EMAIL'::alert_channel],
  email_sent_at    TIMESTAMPTZ,
  whatsapp_sent_at TIMESTAMPTZ,
  in_app_read_at   TIMESTAMPTZ,
  is_read          BOOLEAN DEFAULT false,
  is_actioned      BOOLEAN DEFAULT false,
  is_dismissed     BOOLEAN DEFAULT false,
  actioned_by      UUID REFERENCES users(id),
  actioned_at      TIMESTAMPTZ,
  action_taken     TEXT,
  scheduled_for    TIMESTAMPTZ,
  sent_at          TIMESTAMPTZ,
  expires_at       TIMESTAMPTZ,
  metadata         JSONB DEFAULT '{}',
  created_at       TIMESTAMPTZ DEFAULT NOW()
);
